global.set("name",msg.payload);
var data ="desktop_time,"+

    "mtec_source_time,"+
    "mtec_water_temperature_c,"+
    "mtec_water_flow_l_min,"+
    "mtec_dry_mortar_temp_c,"+
    "mtec_pump_motor_speed_actual_rpm,"+
    "mtec_pump_motor_speed_setpoint_rpm,"+
    "mtec_solenoid_valve_bool,"+
    "mtec_water_pump_bool,"+
    "mtec_mixer_run_bool,"+
    "mtec_water_valve_turns,"+

    "mai_source_time,"+
    "mai_water_run_bool,"+
    "mai_water_temp_c,"+
    "mai_water_flow_set_lh,"+
    "mai_water_flow_actual_lh,"+
    "mai_waterpump_ref_freq_chz,"+
    "mai_waterpump_output_freq_chz,"+
    "mai_mixer_run_bool,"+
    "mai_pump_run_bool,"+
    "mai_pump_speed_chz,"+
    "mai_pump_output_current_da,"+
    "mai_pump_output_power_w,"+
    "mai_pump_vibration_mode_i,"+
    "mai_setting_water_pre_run_s,"+
    "mai_setting_mixer_post_run_s,"+
    "mai_setting_wetprobe_covered_delay_s,"+
    "mai_setting_wetprobe_uncovered_delay_s,"+

    "gantry_source_time,"+
    "gantry_pos_x_mm,"+
    "gantry_pos_y_mm,"+
    "gantry_pos_z_mm,"+
    "gantry_pos_c_deg,"+
    "gantry_vel_x_mm_min,"+
    "gantry_vel_y_mm_min,"+
    "gantry_vel_z_mm_min,"+
    "gantry_vel_c,"+
    "gantry_feedrate_x_mm_min,"+
    "gantry_feedrate_y_mm_min,"+
    "gantry_feedrate_z_mm_min,"+
    "gantry_feedrate_c,"+
    "gantry_feedrate_override_perc,"+
    "gantry_r100,"+
    "gantry_r101,"+
    "gantry_r102,"+
    "gantry_r103,"+
    "gantry_r104,"+
    "gantry_r105,"+
    "gantry_r106,"+
    "gantry_r107,"+
    "gantry_r108,"+
    "gantry_r109,"+

    "material_source_time,"+
    "material_io_ai0_pressure_bar,"+
    "material_io_ai1_pressure_bar,"+
    "material_io_ai0_ma,"+
    "material_io_ai1_ma,"+
    "material_io_ai2_ma,"+
    "material_io_ai3_ma,"+
    "material_io_ai4_ma,"+
    "material_io_ai5_ma,"+
    "material_io_ai6_relative_humidity_perc,"+
    "material_io_ai7_ambient_temperature_c,"+
    "material_io_ao0_ma,"+
    "material_io_ao1_ma,"+
    "material_io_ao2_ma,"+
    "material_io_ao3_ma,"+
    "material_io_di0_bool,"+
    "material_io_di1_bool,"+
    "material_io_di2_bool,"+
    "material_io_di3_bool,"+
    "material_io_do0_bool,"+
    "material_io_do1_bool,"+
    "material_io_do2_bool,"+
    "material_io_do3_bool,"+
    "material_coriolis_mass_flow_kg_min,"+
    "material_coriolis_volume_flow_l_min,"+
    "material_coriolis_density_kg_m3,"+
    "material_coriolis_dynamic_viscocity_cp,"+
    "material_coriolis_temperature_c,"+
    "material_coriolis_exciter_current_0_ma,"+
    "material_coriolis_oscillation_frequency_0_hz,"+
    "material_coriolis_oscillation_amplitude_0_perc,"+
    "material_coriolis_oscillation_damping_0_m_a,"+
    "material_coriolis_signal_asymmetry_perc,"+
    "material_coriolis_exciter_current_1_ma,"+
    "material_coriolis_oscillation_frequency_1_hz,"+
    "material_coriolis_oscillation_amplitude_1_perc,"+
    "material_coriolis_oscillation_damping_1_m_a,"+
    "material_bronkhorst_alarm_info,"+
    "material_bronkhorst_setpoint_gmin,"+
    "material_bronkhorst_measure_gmin,"+
    "material_bronkhorst_temperature,"+
    "material_bronkhorst_density_kg_m3,"+
    "material_bronkhorst_analog_input,"+
    "material_bronkhorst_valve_output,"+
    "material_bronkhorst_setpoint_slope_s,"+
    "material_peristaltic_pump_velocity_rpm,"+
    "material_peristaltic_pump_power_kw,"+
    "material_peristaltic_pump_current_a,"+
    "material_peristaltic_pump_torque_nm,"+
    "material_r0,"+
    "material_r1,"+
    "material_r2,"+
    "material_r3,"+
    "material_r4,"+
    "material_r5,"+
    "material_r6,"+
    "material_r7,"+
    "material_r8,"+
    "material_r9,"+

    "vertico_source_time,"+
    "vertico_is_remote_bool,"+
    "vertico_is_open_loop_bool,"+
    "vertico_actual_motor_velocity_rpm,"+
    "vertico_actual_flow_ml_min,"+
    "vertico_actual_flow_ma,"+
    "vertico_actual_pressure_bar,"+
    "vertico_local_setpoint_open_loop_rpm,"+
    "vertico_local_setpoint_closed_loop_mlmin,"+
    "vertico_remote_start_stop_bool,"+
    "vertico_remote_setpoint_open_loop_rpm,"+
    "vertico_remote_setpoint_closed_loop_mlmin,"+
    "vertico_pid_p,"+
    "vertico_pid_i,"+
    "vertico_pid_d,"+
    "vertico_ai3_ma,"+
    "vertico_ao0_ma,"+
    "vertico_do3_bool,"+
    
    "printhead_source_time,"+
    "printhead_motor_1_motor_1_power_on_bool,"+
    "printhead_motor_1_move_jog_backward_bool,"+
    "printhead_motor_1_move_jog_forward_bool,"+
    "printhead_motor_1_velocity_jog_rpm,"+
    "printhead_motor_1_actual_velocity_rpm,"+
    "printhead_motor_1_actual_power_kw,"+
    "printhead_motor_1_actual_current_a,"+
    "printhead_motor_1_actual_torque_nm,"+
    "printhead_motor_2_power_on_bool,"+
    "printhead_motor_2_move_jog_backward_bool,"+
    "printhead_motor_2_move_jog_forward_bool,"+
    "printhead_motor_2_velocity_jog_rpm,"+
    "printhead_motor_2_actual_velocity_rpm,"+
    "printhead_motor_2_actual_power_kw,"+
    "printhead_motor_2_actual_current_a,"+
    "printhead_motor_2_actual_torque_nm,"+
    "printhead_pressure_bar,"+
    "printhead_box1_io_ai0_ma,"+
    "printhead_box1_io_ai1_ma,"+
    "printhead_box1_io_ai2_ma,"+
    "printhead_box1_io_ai3_ma,"+
    "printhead_box1_io_ai4_ma,"+
    "printhead_box1_io_ai5_ma,"+
    "printhead_box1_io_ai6_ma,"+
    "printhead_box1_io_ai7_ma,"+
    "printhead_box2_io_ai0_ma,"+
    "printhead_box2_io_ai1_ma,"+
    "printhead_box2_io_ai2_ma,"+
    "printhead_box2_io_ai3_ma"+	
    
    "\n"

msg.payload = data

return msg;